version: '3.8'

services:

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepseek-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ./pdfs:/app/pdfs
      - ./vectordb:/app/vectordb
    environment:
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
